package javastock2;

import java.sql.Connection;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.lang.*;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.lang.NullPointerException;
/**
 *
 * @author didie
 */
public class création_article extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst, pstt, pstb;
    ResultSet rs;
    public création_article() {
        initComponents();
        
    }

    @SuppressWarnings({"UseSpecificCatch", "CallToPrintStackTrace"})
    public void Connect(){
        try{
            Class.forName("org.postgresql.Driver");
            con = (Connection)DriverManager.getConnection("jdbc:postgresql://localhost:5432/Javastock","postgres","didier");
            
            
        }catch (Exception e) {
            System.out.println(e);
         /*e.printStackTrace();*/
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numéro = new javax.swing.JLabel();
        txtartic_id = new javax.swing.JTextField();
        txtartic_nom = new javax.swing.JTextField();
        txtartic_categorie = new javax.swing.JComboBox<>();
        txtartic_taille = new javax.swing.JComboBox<>();
        txtartic_couleur = new javax.swing.JComboBox<>();
        txtartic_quantite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtartic_volume = new javax.swing.JTextField();
        txtartic_poids = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtrepas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Libellé:");

        jLabel2.setText("Catégorie:");

        jLabel3.setText("Taille:");

        jLabel4.setText("Couleur:");

        jLabel7.setText("Quantité");

        numéro.setText("Numéro");

        txtartic_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtartic_idActionPerformed(evt);
            }
        });

        txtartic_categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T", "B", "DS", "S" }));
        txtartic_categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtartic_categorieActionPerformed(evt);
            }
        });

        txtartic_taille.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS ", "S ", "M ", "L ", "XL ", "XXL", "null" }));

        txtartic_couleur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanc", "Bleu", "Gris", "Jaune", "Marron", "Noir", "Orange", "Rose", "Rouge", "Vert", "Violet", "null" }));

        txtartic_quantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtartic_quantiteActionPerformed(evt);
            }
        });

        jLabel5.setText("Volume");

        jLabel6.setText("Poids");

        txtartic_volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtartic_volumeActionPerformed(evt);
            }
        });

        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Quitter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Repas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numéro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtartic_poids)
                    .addComponent(txtartic_nom)
                    .addComponent(txtartic_id)
                    .addComponent(txtartic_categorie, 0, 279, Short.MAX_VALUE)
                    .addComponent(txtartic_taille, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtartic_couleur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtartic_quantite)
                    .addComponent(txtartic_volume)
                    .addComponent(txtrepas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numéro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtartic_id, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtartic_nom)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtartic_categorie)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtartic_taille)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtrepas, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtartic_couleur, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtartic_quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtartic_volume, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(txtartic_poids, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 67, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>                        

    @SuppressWarnings("UseSpecificCatch")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        
        
        
        try {
            
            Connect();
            
            
            if("T".equals(txtartic_categorie.getSelectedItem().toString())){
                
                pstb = (PreparedStatement) con.prepareStatement("insert into articles(artic_id,artic_nom,artic_couleur,artic_taille,artic_volume,artic_poids,artic_quantite,artic_categorie, repas) values (?,?,?,?,?,?,?,?,?)");
            
                pst.setInt(1, Integer.parseInt( txtartic_id.getText().trim()));
                pst.setString(2, txtartic_nom.getText());
                pst.setString(3, txtartic_couleur.getSelectedItem().toString());
                pst.setString(4, txtartic_taille.getSelectedItem().toString());
                pst.setInt(5, Integer.parseInt( txtartic_volume.getText().trim()));
                pst.setInt(6, Integer.parseInt( txtartic_poids.getText().trim()));
                pst.setInt(7, Integer.parseInt( txtartic_quantite.getText().trim()));
                pst.setString(8, txtartic_categorie.getSelectedItem().toString());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Article Ajouter");
            }
            if("B".equals(txtartic_categorie.getSelectedItem().toString())){
                
                pstb = (PreparedStatement) con.prepareStatement("insert into articles(artic_id,artic_nom,artic_couleur,artic_taille,artic_volume,artic_poids,artic_quantite,artic_categorie, repas) values (?,?,?,?,?,?,?,?,?)");
                
                pstt.setInt(1, Integer.parseInt( txtartic_id.getText().trim()));
                pstt.setString(2, txtartic_nom.getText());
                pstt.setString(3, txtartic_couleur.getSelectedItem().toString());
                pstt.setString(4, txtartic_taille.getSelectedItem().toString());
                pstt.setInt(5, Integer.parseInt( txtartic_volume.getText().trim()));
                pstt.setInt(6, Integer.parseInt( txtartic_poids.getText().trim()));
                pstt.setInt(7, Integer.parseInt( txtartic_quantite.getText().trim()));
                pstt.setString(8, txtartic_categorie.getSelectedItem().toString());

                pstt.executeUpdate();
                JOptionPane.showMessageDialog(null,"Article Ajouter");
                
            }
            if("DS".equals(txtartic_categorie.getSelectedItem().toString())){
                
                pstb = (PreparedStatement) con.prepareStatement("insert into articles(artic_id,artic_nom,artic_couleur,artic_taille,artic_volume,artic_poids,artic_quantite,artic_categorie, repas) values (?,?,?,?,?,?,?,?,?)");
                
                pstb.setInt(1, Integer.parseInt( txtartic_id.getText().trim()));
                pstb.setString(2, txtartic_nom.getText());
                pstb.setString(3, txtartic_couleur.getSelectedItem().toString());
                pstb.setString(4, txtartic_taille.getSelectedItem().toString());
                pstb.setInt(5, Integer.parseInt( txtartic_volume.getText().trim()));
                pstb.setInt(6, Integer.parseInt( txtartic_poids.getText().trim()));
                pstb.setInt(7, Integer.parseInt( txtartic_quantite.getText().trim()));
                pstb.setString(8, txtartic_categorie.getSelectedItem().toString());

                pstb.executeUpdate();
                JOptionPane.showMessageDialog(null,"Article Ajouter");
                
            }
            if("S".equals(txtartic_categorie.getSelectedItem().toString())){
                
                pstb = (PreparedStatement) con.prepareStatement("insert into articles(artic_id,artic_quantite,artic_categorie, repas) values (?,?,?,?)");
                
                pstb.setInt(1, Integer.parseInt( txtartic_id.getText().trim()));
                pstb.setInt(2, Integer.parseInt( txtartic_quantite.getText().trim()));
                pstb.setString(3, txtartic_categorie.getSelectedItem().toString());
                pstb.setString(4, txtrepas.getText());

                pstb.executeUpdate();
                JOptionPane.showMessageDialog(null,"Article Ajouter");
                
            }
            con.close();
        }
        catch(NumberFormatException ex) {  
            JOptionPane.showMessageDialog(null,"erreur");
        } 
        catch (SQLException ex) {
            Logger.getLogger(création_article.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }                                        

    private void txtartic_idActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtartic_quantiteActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void txtartic_volumeActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        création_article.super.dispose();
            menu_article ma = new menu_article();
            ma.setVisible(true);
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void txtartic_categorieActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(création_article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(création_article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(création_article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(création_article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       /* try {
            Class.forName("org.postgresql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/test", "postgres","didier");
            
            Statement stmt = conn.createStatement();
            ResultSet res = stmt.executeQuery("Select * from article");
            
            while(res.next())
                System.out.println(res.getInt(1)+"  "+res.getString(2)+"  "+res.getString(3));
            conn.close();
            
            
        }
        catch(Exception e) {
            System.out.println(e);
        } */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new création_article().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel numéro;
    private javax.swing.JComboBox<String> txtartic_categorie;
    private javax.swing.JComboBox<String> txtartic_couleur;
    private javax.swing.JTextField txtartic_id;
    private javax.swing.JTextField txtartic_nom;
    private javax.swing.JTextField txtartic_poids;
    private javax.swing.JTextField txtartic_quantite;
    private javax.swing.JComboBox<String> txtartic_taille;
    private javax.swing.JTextField txtartic_volume;
    private javax.swing.JTextField txtrepas;
    // End of variables declaration                   
}
